        !COMPILER-GENERATED INTERFACE MODULE: Tue Mar 05 11:34:26 2024
        MODULE INVERT1__genmod
          INTERFACE 
            SUBROUTINE INVERT1(AA)
              COMPLEX(KIND=4) :: AA(6,6)
            END SUBROUTINE INVERT1
          END INTERFACE 
        END MODULE INVERT1__genmod
