        !COMPILER-GENERATED INTERFACE MODULE: Tue Mar 05 11:34:26 2024
        MODULE PPROP__genmod
          INTERFACE 
            SUBROUTINE PPROP
            END SUBROUTINE PPROP
          END INTERFACE 
        END MODULE PPROP__genmod
